### ISSUE TITLE
404 Error on Website

### ISSUE THREAD

**Issue by traitortots** [mchaynes/geodatadownloader#44]
As of 7/18/2023, navigating to the site returns a 404 error message.

**Comment by mchaynes** [comment]
Oh wow, thanks for letting me know. Looking into this now.

**Comment by mchaynes** [comment]
@traitortots, looks to be fixed now. Can you confirm?

**Comment by traitortots** [comment]
@mchaynes Yep, works for me now! Thanks!

**Comment by mchaynes** [comment]
Sweet, thank you. Gonna close this now. 

Lemme know if there's any features you'd like added btw!! 😊

**Comment by traitortots** [comment]
Will do!
