### ISSUE TITLE
Support bulk downloading list of links

### ISSUE THREAD

**Issue by Theinatorinator** [mchaynes/geodatadownloader#62]
Essentially I have a CSV of links, each link I can put into the tool and it downloads properly. I want to be able to just put the entire list in.

**Comment by mchaynes** [comment]
Hello! Thanks for filing the issue.

This is a good feature I'd like to add. Your solution definitely works, but bulk workloads are something I'd like to support, especially if there are people asking for it.

**Comment by mchaynes** [comment]
Going to call this fixed with this PR: https://github.com/mchaynes/geodatadownloader/pull/65
